[package]
name = "josekit"
version = "0.3.0"
description = "JOSE (Javascript Object Signing and Encryption) library for Rust."
homepage = "https://github.com/hidekatsu-izuno/josekit-rs"
repository = "https://github.com/hidekatsu-izuno/josekit-rs"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = ["Hidekatsu Izuno <hidekatsu.izuno@gmail.com>"]
keywords = ["joes", "jwt", "jws", "jwa", "web"]
categories = ["authentication"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
anyhow = "1"
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
base64 = "0.12"
chrono = "0.4"
openssl = { version = "0.10" }
openssl-sys = { version = "0.9" }
