[package]
name = "jwt_rs"
version = "0.1.0"
description = "JWT (JSON Web Token) library for rust (based on OpenSSL)."
homepage = "https://github.com/hidekatsu-izuno/jwt-rs"
repository = "https://github.com/hidekatsu-izuno/jwt-rs"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = ["Hidekatsu Izuno <hidekatsu.izuno@gmail.com>"]
keywords = ["jwt", "web"]
categories = ["authentication"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.16"
anyhow = "1.0.28"
lazy_static = "1.4.0"
bit-vec = "0.6.2"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
base64 = "0.12.0"
chrono = "0.4.11"
openssl-sys = "0.9"
openssl = "0.10"
