[package]
name = "jwt_rs"
version = "0.1.0"
description = "JWT (JSON Web Token) library for rust (based on OpenSSL)."
homepage = "https://github.com/hidekatsu-izuno/jwt-rs"
license = "MIT OR Apache-2.0"
authors = ["Hidekatsu Izuno <hidekatsu.izuno@gmail.com>"]
keywords = ["jwt", "web"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.16"
anyhow = "1.0.28"
serde_json = { version = "1.0", features = ["preserve_order"] }
base64 = "0.12.0"
openssl-sys = "0.9"
openssl = "0.10"
